<?php

namespace DoctrineProxies\__CG__\Chamilo\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Language extends \Chamilo\CoreBundle\Entity\Language implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'id', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'originalName', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'englishName', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'isocode', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'dokeosFolder', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'available', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'parent', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'subLanguages'];
        }

        return ['__isInitialized__', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'id', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'originalName', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'englishName', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'isocode', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'dokeosFolder', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'available', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'parent', '' . "\0" . 'Chamilo\\CoreBundle\\Entity\\Language' . "\0" . 'subLanguages'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Language $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setOriginalName($originalName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalName', [$originalName]);

        return parent::setOriginalName($originalName);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalName', []);

        return parent::getOriginalName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnglishName($englishName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnglishName', [$englishName]);

        return parent::setEnglishName($englishName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnglishName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnglishName', []);

        return parent::getEnglishName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsocode($isocode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsocode', [$isocode]);

        return parent::setIsocode($isocode);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsocode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsocode', []);

        return parent::getIsocode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDokeosFolder($dokeosFolder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDokeosFolder', [$dokeosFolder]);

        return parent::setDokeosFolder($dokeosFolder);
    }

    /**
     * {@inheritDoc}
     */
    public function getDokeosFolder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDokeosFolder', []);

        return parent::getDokeosFolder();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailable($available)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailable', [$available]);

        return parent::setAvailable($available);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailable', []);

        return parent::getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Chamilo\CoreBundle\Entity\Language $parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubLanguages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubLanguages', []);

        return parent::getSubLanguages();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
